### ISSUE TITLE
installing as a plugin fails

### ISSUE THREAD

**Issue by vegarringdal** [aurelia-ui-toolkits/aurelia-v-grid#23]
@Thanood @JeroenVinke : Anything special we need to do to make work as normal plugin? 

This should have worked fine with normal es2016 skeleton ?
```
 jspm install aurelia-v-grid=github:aurelia-ui-toolkits/aurelia-v-grid
```

Wanted to ask before using to much time on it, in case you have the answer already :-)

```
system.src.js:4597 GET http://127.0.0.1:9000/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@master.js 404 (Not Found)I 
system.js:4 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://127.0.0.1:9000/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@master.js(…)
```

**Comment by Thanood** [comment]
Try running jspm build-release and push the result to the main repo.
Sorry, I somehow forgot about that.

**Comment by Thanood** [comment]
The reason is: jspm looks for the `dist` folder because of this setting: https://github.com/aurelia-ui-toolkits/aurelia-v-grid/blob/master/package.json#L32-L35

But you don't populate `dist` until you run `gulp build-release`.

That's a convenience feature of the build system because otherwise you would have to sort out `dist` on every git commit.

**Comment by vegarringdal** [comment]
@Thanood 
Thanks for clearing that one up.
Ill give it a go later today.

**Comment by Thanood** [comment]
Sorry, of course that's `gulp build-release` :smile:

**Comment by vegarringdal** [comment]
```gulp build-release``` worked, thx
