### ISSUE TITLE
Auto generate column feature

### ISSUE THREAD

**Issue by shaunn-mukmen** [aurelia-ui-toolkits/aurelia-v-grid#43]
Hello, 

I want to consume vgrid with remote data, with column config populated from response fields.
For instance, if I'm getting 
[
{Name: john, age:23},
{Name:Alice,age:29}
]

My colConfig should be populated by introspecting the data and show two columns: name and age.
Is that possible today? If so, please point me to sample code.
Hope I'm making myself clear.
Shaunn

**Comment by vegarringdal** [comment]
You closed the issue right away ?
Grid dont have a magical function for this, but Im sure it will be possible to create something.
Im without net next days so its kinda hard for me to create a gist to test workarounds for you atm

**Comment by Thanood** [comment]
@Naive-user123 
Maybe you could use [column.bind](https://aurelia-ui-toolkits.gitbooks.io/aurelia-v-grid-docs/content/chap03/column-bind.html) to implement this.

I'm not sure if this should be built in the grid because there are a lot of variations on what a user would expect to happen from this. For example: what happens to incomplete data sets (undefined properties in the input objects)? Or properties that should be private..

On the other hand, this would be a nice convenient feature and users could prepare the collection before passing it to the grid (which probably would introduce a performance hit) or they could just be sure that.

**Comment by vegarringdal** [comment]
Here is  a gist on how to set columns after its created.
https://gist.run/?id=d1e49247ce37f677ca4a04ca65d38cbf

**Comment by vegarringdal** [comment]
Updated gist to newest aurelia and new grid release
Change columns is simpler now
